- include_tasks: RedHat.yml
  when: "ansible_os_family == 'RedHat' and use_distro_packaging"

- include_tasks: Debian.yml
  when: "ansible_os_family == 'Debian' and use_distro_packaging"

- include_tasks: Raw.yml
  when: "not use_distro_packaging"
