- name: uninstall the distro etcd
  apt: name=etcd state=absent
  when: "ansible_os_family == 'Debian'"

- name: put the config file
  template: src=etcd dest=/etc/default/etcd backup=yes
  notify: restart etcd

- name: get etcd in binary form
  get_url: url=https://github.com/coreos/etcd/releases/download/v{{ etcd_binary_version }}/etcd-v{{ etcd_binary_version }}-linux-amd64.tar.gz dest=/root/etcd-v{{ etcd_binary_version }}-linux-amd64.tar.gz

- name: unpack binary etcd
  unarchive: copy=no src="/root/etcd-v{{ etcd_binary_version }}-linux-amd64.tar.gz" dest=/opt

- name: create a user
  user: name={{ etcd_user }}

- name: create "{{ etcd_data_dir }}"
  file: owner={{ etcd_user }} dest="{{ etcd_data_dir }}" state=directory

- name: put a service descriptor
  template: src=etcd.service dest=/etc/systemd/system/etcd-{{ etcd_binary_version }}.service owner=root group=root mode=0644

- name: start etcd service
  service: name=etcd-{{ etcd_binary_version }} state=started enabled=yes
