- name: systemctl daemon-reload
  shell: systemctl daemon-reload

- name: restart etcd
  service: name=etcd state=restarted

- name: restart etcd-{{ etcd_binary_version }}
  service: name=etcd-{{ etcd_binary_version }} state=restarted
